apiVersion: apps/v1
kind: Deployment
metadata:
  name: know-comments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: know-comments
  template:
    metadata:
      labels:
        app.kubernetes.io/name: know-comments
        app.kubernetes.io/instance: all
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: back
        app.kubernetes.io/part-of: know-mini
        app.kubernetes.io/managed-by: skaffold
      name: know-comments
    spec:
      containers:
        - image: michaelact/know-comments:latest
          name: comments
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: env-know-comments
            - configMapRef:
                name: env-know-discovery
      restartPolicy: Always
