apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: know-comments
    app.kubernetes.io/instance: all
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: back
    app.kubernetes.io/part-of: know-mini
    app.kubernetes.io/managed-by: skaffold
  name: know-comments
spec:
  ports:
    - name: comments
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: know-comments
