apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: know-client
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: know-client
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: know-client
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 9898
  analysis:
    interval: 10s
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.ingress-nginx/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://know-client-canary:3000/"
